In [ ]:
# Matrix Multip

In [45]:
import numpy as np
a = np.matrix([0,3,5,5,5,2]).reshape(2,3)
a

b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
b

print(a*b)

prod = np.matmul(np.array(a),np.array(b))
print(prod)

print("short form ", a@b)


[[ 29 -16]
 [ 38   6]]
[[ 29 -16]
 [ 38   6]]
short form  [[ 29 -16]
 [ 38   6]]


In [ ]:
# Stacking

In [46]:
import numpy as np 
x = np.arange(4).reshape(2,2)
print(x)
y = np.arange(4,8).reshape(2,2)
print(y)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [59]:
z= np.hstack((x,y))
z

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [60]:
g = np.vstack((x,y))
g

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [61]:
# Concat
w = np.concatenate((x,y), axis=1)
print(w)

[[0 1 4 5]
 [2 3 6 7]]


In [51]:
z = np.hstack((x,y))
z == w

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
d = np.dstack((x,y))
print(d.shape)

(2, 2, 2)


In [63]:
np.column_stack((x,y)) == np.hstack((x,y))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
np.row_stack((x,y)) == np.vstack((x,y))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])